### ISSUE TITLE
Step 4.2 returns error - no link app is started

### ISSUE THREAD

**Issue by ChristianKa** [wavezcs/SonicPadObico#6]
At Step 4.2 when I enter 
`python3 -m moonraker_obico.link -c /usr/share/moonraker-obico/moonraker-obico.cfg`
it returns the following:
```
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/share/moonraker-obico/moonraker_obico/link.py", line 36, in <module>
    config = Config(args.config_path)
  File "/usr/share/moonraker-obico/moonraker_obico/config.py", line 183, in __init__
    self.webcam = WebcamConfig(webcam_config_section=config['webcam'])
  File "/usr/lib/python3.7/configparser.py", line 958, in __getitem__
    raise KeyError(key)
KeyError: 'webcam'
```

Any support would be really appreciated 🙏

**Comment by ChristianKa** [comment]
OK, have found the issue(s).
In Step 2.2 after creating the moonraker-obico.cfg I needed to 
1. google for the original (https://www.obico.io/docs/user-guides/moonraker-obico/config/)  
2. add the content to the file using vim. 
3. Replace the host IP in the moonraker settings with the sonic pad IP
4. save the file with :wq

Before continuing with Steps 3.1 I needed to 
"pip3 install virtualenv"
to enable the commands in the following steps.

In Step 5 ignore everything and read the comments from fran6p in this issue:
https://github.com/wavezcs/SonicPadObico/issues/5#issuecomment-1435727108

Editing the obico-start.sh and  /etc/rc.local according to this
https://github.com/wavezcs/SonicPadObico/issues/5#issuecomment-1445050674 

worked and now obico starts automatically.
